webtalk_init -webtalk_dir /home/wes/Documents/computerEngineering/ComputerEngineering-Project-1/computer_assignment_2/computer_assignment_2.sim/sim_1/behav/xsim/xsim.dir/encoder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 24 00:15:09 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fccc10ff-1f9b-44a7-84c4-079862e198c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4966a034ab164ccbba28ad04fc72bfa5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "elementary" -context "user_environment"
webtalk_add_data -client project -key os_release -value "elementary OS 0.4.1 Loki" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2250.531 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132328_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1890986613 -regid "" -xml /home/wes/Documents/computerEngineering/ComputerEngineering-Project-1/computer_assignment_2/computer_assignment_2.sim/sim_1/behav/xsim/xsim.dir/encoder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/wes/Documents/computerEngineering/ComputerEngineering-Project-1/computer_assignment_2/computer_assignment_2.sim/sim_1/behav/xsim/xsim.dir/encoder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/wes/Documents/computerEngineering/ComputerEngineering-Project-1/computer_assignment_2/computer_assignment_2.sim/sim_1/behav/xsim/xsim.dir/encoder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
